name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit:
    name: Unit Test (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node: [16]
        
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v4
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.code }}-${{ hashFiles('**/package-lock.json') }}

      - name: Run test
        run: |
          npm install
          npm run test