name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit:
    name: Unit Test (Node.js v16)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
      
      - name: Run test
        run: |
          npm install
          npm run test